spring:
  data:
    mongodb:
      uri: mongodb://mimosa:filter@localhost:27017/?authSource=admin
      database: deep_pokemon_dev_env
      timeZone: GMT+8
    redis:
      host: localhost
      port: 6379
      timeout: 100
  #禁用templates缓存，方便hotswap
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 8695141a127c27b88038
            clientSecret: 444f832070893a506a3479b66ef3e9a3ca2c90ee
  web:
    cors: "*"
logging:
  config: classpath:logback.xml
server:
  tomcat:
    accesslog:
      enabled: true
      directory: /logs/access

# ...